title: DAZ Sentinel
description: Red Team | OT Security | Critical Infrastructure | EPC Project Controls
author: Damian Stępień
baseurl: ""
url: "https://dazds.github.io"
theme: jekyll-theme-cayman
markdown: kramdown
permalink: /:categories/:title/

header_pages:
  - _pages/services.md
  - _pages/about.md
  - writeups/README.md
  - articles/README.md
  - progress/README.md
  - certifications/README.md
  - _pages/contact.md
